### ISSUE TITLE
Fresh install, error with oxocarbon on opening nvim

### ISSUE THREAD

**Issue by dawnonmercury** [shaunsingh/nyoom.nvim#43] opened 2022-07-30 20:50 UTC
On a fresh install, I get the following error when opening nvim. Seems to be a problem finding oxocarbon.

```
Error detected while processing /home/dawn/git/nyoom.nvim/init.lua:
E5113: Error while calling lua chunk: ....cache/nvim/hotpot/home/dawn/git/nyoom.nvim/fnl/init.lua:52: module 'oxocarbon' not found:
        no field package.preload['oxocarbon']
        no file './oxocarbon.lua'
        no file '/home/dawn/git/neovim/.deps/usr/share/luajit-2.1.0-beta3/oxocarbon.lua'
        no file '/usr/local/share/lua/5.1/oxocarbon.lua'
        no file '/usr/local/share/lua/5.1/oxocarbon/init.lua'
        no file '/home/dawn/git/neovim/.deps/usr/share/lua/5.1/oxocarbon.lua'
        no file '/home/dawn/git/neovim/.deps/usr/share/lua/5.1/oxocarbon/init.lua'
        no file '/home/dawn/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/oxocarbon.lua'
        no file '/home/dawn/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/oxocarbon/init.lua'
        no file '/home/dawn/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/oxocarbon.lua'
        no file '/home/dawn/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/oxocarbon/init.lua'
        no file './oxocarbon.so'
        no file '/usr/local/lib/lua/5.1/oxocarbon.so'
        no file '/home/dawn/git/neovim/.deps/usr/lib/lua/5.1/oxocarbon.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/dawn/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/oxocarbon.so'
stack traceback:
        [C]: in function 'require'
        ....cache/nvim/hotpot/home/dawn/git/nyoom.nvim/fnl/init.lua:52: in main chunk
        [C]: in function 'require'
        /home/dawn/git/nyoom.nvim/init.lua:2: in main chunk
```
Notably, when `(set! colorscheme "muses")` was still in `options.fnl`, the following error comes up on entering nvim instead.

```Error detected while processing /home/dawn/git/nyoom.nvim/init.lua:
E5113: Error while calling lua chunk: ...vim/hotpot/home/dawn/git/nyoom.nvim/fnl/core/options.lua:78: attempt to call global 'colorscheme' (a nil value)
stack traceback:
        ...vim/hotpot/home/dawn/git/nyoom.nvim/fnl/core/options.lua:78: in main chunk
        [C]: in function 'require'
        ...e/nvim/hotpot/home/dawn/git/nyoom.nvim/fnl/core/init.lua:5: in main chunk
        [C]: in function 'require'
        ....cache/nvim/hotpot/home/dawn/git/nyoom.nvim/fnl/init.lua:51: in main chunk
        [C]: in function 'require'
        /home/dawn/git/nyoom.nvim/init.lua:2: in main chunk
```

**Comment by shaunsingh** [comment] 2022-07-30 21:23
> package.preload['oxocarbon']

Thanks for the report. I'm currently working on moving oxocarbon into its own plugin, so the issue shouldn't occur anymore once I roll out the update this afternoon

> (set! colorscheme "muses")

The issue is this expands to `vim.opt.colorsche`, which doesn't exist. You can use the `colorscheme` macro instead:

```fennel
(import-macros {: colorscheme} :macros.highlight-macros)
(colorscheme muses)
```

**Comment by shaunsingh** [comment] 2022-07-30 21:29
Oxocarbon issue should be fixed now as well (moved into its own plugin)

**Comment by dawnonmercury** [comment] 2022-07-30 21:58
Ok everything seems to work now, both my own colorscheme and oxocarbon

**Closed** 2022-07-31 02:02 UTC

**Comment by icyrogue** [comment] 2022-07-31 23:27
Still throws that exact error on install

**Comment by Icy-Thought** [comment] 2022-07-31 23:36
I wonder if there is something wrong with your installation @icyrogue, because I installed nyoom.nvim a couple of hours ago and it had no complaints.

**Comment by icyrogue** [comment] 2022-07-31 23:53
> I wonder if there is something wrong with your installation @icyrogue, because I installed nyoom.nvim a couple of hours ago and it had no complaints.

Turned out to be packer problem, packer folder was created, so install script was failing, just had to delete it again and reinstall
