### ISSUE TITLE
module `cmp_nvim_lsp` not found

### ISSUE THREAD

**Issue by wizard-28** [shaunsingh/nyoom.nvim#6] opened 2022-02-20 17:56 UTC
I'm getting this error after freshly installing the config, and ran `:PackerSync`

```lua
..im/hotpot/home/pop-os/.config/nvim/fnl/conf/pack/lsp.lua:24: module 'cmp_nvim_lsp' not found:
	no field package.preload['cmp_nvim_lsp']
	no file '/home/pop-os/.cache/nvim/hotpot//home/pop-os/.local/share/nvim/site/pack/packer/start/hotpot.nvim/fnl/cmp_nvim_lsp.lua'
	no file './cmp_nvim_lsp.lua'
	no file '/usr/share/luajit-2.1.0-beta3/cmp_nvim_lsp.lua'
	no file '/usr/local/share/lua/5.1/cmp_nvim_lsp.lua'
	no file '/usr/local/share/lua/5.1/cmp_nvim_lsp/init.lua'
	no file '/usr/share/lua/5.1/cmp_nvim_lsp.lua'
	no file '/usr/share/lua/5.1/cmp_nvim_lsp/init.lua'
	no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp_nvim_lsp.lua'
	no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp_nvim_lsp/init.lua'
	no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp_nvim_lsp.lua'
	no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp_nvim_lsp/init.lua'
	no file './cmp_nvim_lsp.so'
	no file '/usr/local/lib/lua/5.1/cmp_nvim_lsp.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cmp_nvim_lsp.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/cmp_nvim_lsp.so'
```

**Comment by shaunsingh** [comment] 2022-02-21 21:28
I couldn't reproduce this issue myself, but I've moved cmp-nvim-lsp as a require plugin for lspconfig, so it should be fixed. Can you kindly try the latest commit and see if the issue persists?

**Comment by DanisDGK** [comment] 2022-02-22 08:13
I came across this issue as well and had the same idea as a fix, and it does fix this specific issue, however, after that, Neovim still can't find several others as well, such as cmp itself and conjure.

I haven't had the time to spend figuring out how to fix, but I thought I'd just mention it here anyway.

**Comment by wizard-28** [comment] 2022-02-22 10:00
New error with `cmp` not found
```lua
Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: module 'cmp' not found:
        no field package.preload['cmp']
        no file '/home/pop-os/.cache/nvim/hotpot//home/pop-os/.local/share/nvim/site/pack/packer/start/hotpot.nvim/fnl/cmp.lua'
        no file './cmp.lua'
        no file '/usr/share/luajit-2.1.0-beta3/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp/init.lua'
        no file '/usr/share/lua/5.1/cmp.lua'
        no file '/usr/share/lua/5.1/cmp/init.lua'
        no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp.lua'
        no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp/init.lua'
        no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp.lua'
        no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp/init.lua'
        no file './cmp.so'
        no file '/usr/local/lib/lua/5.1/cmp.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cmp.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/pop-os/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/cmp.so'
stack traceback:
        [C]: in function 'require'
        ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: in function '_on_insert_enter'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

This happens just when I go into insert mode. I've reinstalled nyoom.

**Comment by shaunsingh** [comment] 2022-02-27 19:40
I removed the lazy loading for CMP in https://github.com/shaunsingh/nyoom.nvim/commit/24a9b2d98d42838d8122475e81f7ef846270c12f. 
- lspconfig requires cmp-nvim-lsp as a dep now, so I think that should be fixed
- any other providers should load immediately as opposed to `InsertEnter` now. 

LMK if the issue is still there

**Comment by wizard-28** [comment] 2022-02-28 05:50
Seems to be fixed for me! But I get https://github.com/shaunsingh/nyoom.nvim/issues/14 on startup now.

**Closed** 2022-02-28 19:40 UTC
